package com.ghaniram.zoya

import android.content.ClipData as AndroidClipData
import android.content.ClipboardManager as AndroidClipboardManager
import android.content.Context as AndroidContext
import org.json.JSONArray
import org.json.JSONObject

// Compatibility aliases for source generated by the repair scripts.
typealias Context = AndroidContext
typealias ClipboardManager = AndroidClipboardManager
typealias ClipData = AndroidClipData

/** Compatibility name used by GeminiLiveClient; the service's real implementation is captureScreenVisionFrame. */
fun AccessibilityControlService.captureScreenJpeg(onCaptured: (ByteArray) -> Unit) {
    captureScreenVisionFrame(onCaptured)
}

/** Missing settings exposed as extensions so the existing persistent store remains backward compatible. */
var AnuSettingsStore.triggerWifiLost: Boolean
    get() = prefsCompat().getBoolean("trig_wifi_lost", false)
    set(value) { prefsCompat().edit().putBoolean("trig_wifi_lost", value).apply() }

var AnuSettingsStore.triggerAirplaneModeOn: Boolean
    get() = prefsCompat().getBoolean("trig_airplane_on", true)
    set(value) { prefsCompat().edit().putBoolean("trig_airplane_on", value).apply() }

var AnuSettingsStore.triggerAirplaneModeOff: Boolean
    get() = prefsCompat().getBoolean("trig_airplane_off", true)
    set(value) { prefsCompat().edit().putBoolean("trig_airplane_off", value).apply() }

var AnuSettingsStore.triggerPhoneOnSilent: Boolean
    get() = prefsCompat().getBoolean("trig_phone_silent", false)
    set(value) { prefsCompat().edit().putBoolean("trig_phone_silent", value).apply() }

var AnuSettingsStore.triggerRingerBackOn: Boolean
    get() = prefsCompat().getBoolean("trig_ringer_back_on", false)
    set(value) { prefsCompat().edit().putBoolean("trig_ringer_back_on", value).apply() }

var AnuSettingsStore.triggerAppInstalled: Boolean
    get() = prefsCompat().getBoolean("trig_app_installed", false)
    set(value) { prefsCompat().edit().putBoolean("trig_app_installed", value).apply() }

var AnuSettingsStore.triggerAppUninstalled: Boolean
    get() = prefsCompat().getBoolean("trig_app_uninstalled", false)
    set(value) { prefsCompat().edit().putBoolean("trig_app_uninstalled", value).apply() }

var AnuSettingsStore.mapsApiKey: String
    get() = prefsCompat().getString("maps_api_key", "") ?: ""
    set(value) { prefsCompat().edit().putString("maps_api_key", value).apply() }

var AnuSettingsStore.smartGeofencingEnabled: Boolean
    get() = prefsCompat().getBoolean("smart_geofencing_enabled", false)
    set(value) { prefsCompat().edit().putBoolean("smart_geofencing_enabled", value).apply() }

var AnuSettingsStore.weatherProvider: String
    get() = prefsCompat().getString("weather_provider", "Open-Meteo") ?: "Open-Meteo"
    set(value) { prefsCompat().edit().putString("weather_provider", value).apply() }

private fun AnuSettingsStore.prefsCompat() =
    javaClass.getDeclaredField("prefs").let { field ->
        field.isAccessible = true
        field.get(this) as android.content.SharedPreferences
    }

fun AnuSettingsStore.exportBackupJson(memories: List<String>, messagesCount: Int): String {
    val root = JSONObject()
    root.put("app", "Anu")
    root.put("version", "4.0.0")
    root.put("timestamp", System.currentTimeMillis())
    root.put("memories", JSONArray().apply { memories.forEach { put(it) } })
    root.put("conversations_count", messagesCount)
    root.put("settings", JSONObject(exportSettingsJson()))
    return root.toString(2)
}
