name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore anu-release.jks \
            -alias anu \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "MyStrongPass123" \
            -keypass "MyStrongPass123" \
            -dname "CN=Ghani, OU=Anu, O=Anu, L=Mayurbhanj, S=Odisha, C=IN"

      - name: Print SHA256 fingerprint
        run: |
          keytool -list -v -keystore anu-release.jks -alias anu -storepass "MyStrongPass123" | grep "SHA256:"

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: anu-release-keystore
          path: anu-release.jks
